apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: student-app-backend
  template:
    metadata:
      labels:
        app: student-app-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: student-db-svc