apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: student-app-frontend
  template:
    metadata:
      labels:
        app: student-app-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80